displayName: Custom Case Sensitive Headers
type: middleware
iconPath: .assets/icon.png

import: github.com/ashishsinghdev/traefik-middleware-case-sensitive-headers

summary: 'Custom Case Sensitive Headers'

testData:
  headers:
    addHeaders:
    - name: X-To-Add-Header-1
      value: X-To-Add-Header-1-Value
    - name: X-To-Add-Header-2
      value: X-To-Add-Header-2-Value
    removeHeaders:
      names:
      - X-To-Remove-Header-1
      - X-To-Remove-Header-2
    modifyHeaders:
    - from: Authorization
      to: X-Auth
      prefix: Bearer 
      suffix: ;
      removeOriginal: true
      overwriteIfExist: false
    - from: X-Client-Cert
      to: SSL_CLIENT_CERT
      prefix: -----BEGIN CERTIFICATE-----
      suffix: -----END CERTIFICATE-----
      removeOriginal: false
      overwriteIfExist: true
